In [30]:
# Homework 5.5




# MATRIX MANIPULATION
# 1. Use the invertible matrix theorem to show that both $A$ and $B$ are invertible (hint: it suffices to 
# show that the columns are linearly independent or to show that the determinant is not zero).

# creating the matrices

x <- c(1,3,2,4)
A <- matrix(x, nrow = 2, ncol=2)
A

y <- c(5,7,6,8)
B <- matrix(y, nrow = 2, ncol=2)
B
# to show that they are invertable I will use det(A) /= 0 [ad-bc /= 0]

Test_invertable <- function(x){
    if (det(x)==0){
        print('is not invertable')
}
    else {
        print('is invertable')
}}

Test_invertable(A)
Test_invertable(B)
# question: How can I turn it into "A is invtertable"; I tried prinf but that does not work


[,1] [,2]
[1,]    1    2
[2,]    3    4

[,1] [,2]
[1,]    5    6
[2,]    7    8

[1] "is invertable"
[1] "is invertable"


In [54]:
# 2.Calculate by hand the matrices A^{-1} and B^{-1}.

Inverse <- function(A){
    1/((A[1,1] * A[2,2])-(A[1,2] * A[2,1])) * matrix(c(A[2,2], -(A[2,1]), -(A[1,2]), A[1,1]), nrow = 2, ncol = 2)
    }
Inverse(A)
Inverse(B)


[,1] [,2]
[1,] -2.0  1.0
[2,]  1.5 -0.5

[,1] [,2]
[1,] -4.0  3.0
[2,]  3.5 -2.5

In [85]:
# 3. Use a for loop to create a vector containing the entries in $A$,
# then use the matrix function to convert your vector into the matrix
# $A$. Do the same for #$B$.

c <- rep(0, times=3)
c[1] = 1
for(t in 1:3){
        c[t+1] <- c[t]+1
}
A <- matrix(c, ncol=2, nrow=2, byrow = TRUE)
A

c <- rep(0, times=3)
c[1] = 5
for(t in 1:3){
        c[t+1] <- c[t]+1
}
B <- matrix(c, ncol=2, nrow=2, byrow = TRUE)
B

[,1] [,2]
[1,]    1    2
[2,]    3    4

[,1] [,2]
[1,]    5    6
[2,]    7    8

In [103]:
# 4. Create a $2 \times 2$ matrix of zeros, then using nested for loops,
# loop over individual entries of this matrix filling in the values for $A$.
# Do the same for $B$.

M0 <- matrix(c(rep(0,4)), nrow=2, ncol=2)
M0


[,1] [,2]
[1,]    0    0
[2,]    0    0

In [105]:
# STATISTICAL FUNCTIONS
# 1.Can a computer generate a random number? Why or why not?

# http://www.howtogeek.com/183051/htg-explains-how-computers-generate-random-numbers/ 
# https://en.wikipedia.org/wiki/Random_number_generation
# They are often initialized using a computer's real time clock as the seed, since such a clock generally measures in milliseconds, far beyond the person's precision. These functions may provide enough randomness for certain tasks (for example video games) but are unsuitable where high-quality randomness is required, such as in cryptography applications, statistics or numerical analysis.
# I get the intuition but: Seed?

In [107]:
# 2. From what distribution does a random number generater draw? 
# How does the computer convert from this distribution to whatever distribution you specify?

# Real Answer: Uses Uniform Distributed x~U(a,b) --> everything between 




#https://www.random.org/gaussian-distributions/
#This form allows you to generate random numbers from a Gaussian distribution (also known as a normal distribution). The randomness comes from atmospheric noise, which for many purposes is better than the pseudo-random number algorithms typically used in computer programs. The form uses a Box-Muller Transform to generate the Gaussian distribution from uniformly distributed numbers.


In [109]:
# 3. What package did we use in class to generate random numbers more easily?
# runif()

In [111]:
# 4. Type data() into R to see a list of built in data sets.
data()

In [12]:
# 6. Use the runif function to generate $\mathbf{x}$, a random vector of length $100$ whose entries
# $x_i \sim U(0, 2)$ in one line.

T <- 100
c <- runif(T, 0, 2)

# 7. Define a value $p$ and another vector $y$ such that if an entry in $\mathbf{x}$ is bigger than $p$, the
# corresponding entry in $y$ is $0$ and $1$ otherwise. Use a for loop combined with an if statement to fill y.

p <- 1.2
y <- rep(0, T)

for(t in 1:T){
    if(c[t]<=p){
        y[t]=1
    } else {
        y[t]=0
    }
}
y


[1] 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 1 0 1 0 1 1 0 1 1
 [38] 0 0 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0
 [75] 1 1 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1

In [20]:
# 8. Do the same as above using the sample function in one line.

sample(seq(0,1), T, replace = TRUE, prob = c(0.4, 0.6))



[1] 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0
 [38] 0 1 0 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 0
 [75] 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 0 1 0

In [21]:
# 9. Use rnorm to generate a vector z of $100$ random numbers distributed $\mathcal{N}(1.0, 2.0)$ in one line.

rnorm

Normal                  package:stats                  R Documentation

_T_h_e _N_o_r_m_a_l _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Density, distribution function, quantile function and random
     generation for the normal distribution with mean equal to 'mean'
     and standard deviation equal to 'sd'.

_U_s_a_g_e:

     dnorm(x, mean = 0, sd = 1, log = FALSE)
     pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     rnorm(n, mean = 0, sd = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If 'length(n) > 1', the length is
          taken to be the number required.

    mean: vector of means.

      sd: vector of standard deviations.

log, log.p: logical; if TRUE, probabilities p are given as log(p).

lower.tail: logical; if TRUE (default), probabilities are P[X <= x]
          otherwise, P[X > x].

_D_e_t_a_i_l_s:

     If 'mean' or 'sd' are not specified they assume the default values
     of '0' and '1', respectively.

     The normal distribution has density

            f(x) = 1/(sqrt(2 pi) sigma) e^-((x - mu)^2/(2 sigma^2))     
     
     where mu is the mean of the distribution and sigma the standard
     deviation.

_V_a_l_u_e:

     'dnorm' gives the density, 'pnorm' gives the distribution
     function, 'qnorm' gives the quantile function, and 'rnorm'
     generates random deviates.

     The length of the result is determined by 'n' for 'rnorm', and is
     the maximum of the lengths of the numerical arguments for the
     other functions.

     The numerical arguments other than 'n' are recycled to the length
     of the result.  Only the first elements of the logical arguments
     are used.

     For 'sd = 0' this gives the limit as 'sd' decreases to 0, a point
     mass at 'mu'.  'sd < 0' is an error and returns 'NaN'.

_S_o_u_r_c_e:

     For 'pnorm', based on

     Cody, W. D. (1993) Algorithm 715: SPECFUN - A portable FORTRAN
     package of special function routines and test drivers.  _ACM
     Transactions on Mathematical Software_ *19*, 22-32.

     For 'qnorm', the code is a C translation of

     Wichura, M. J. (1988) Algorithm AS 241: The percentage points of
     the normal distribution.  _Applied Statistics_, *37*, 477-484.

     which provides precise results up to about 16 digits.

     For 'rnorm', see RNG for how to select the algorithm and for
     references to the supplied methods.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     Johnson, N. L., Kotz, S. and Balakrishnan, N. (1995) _Continuous
     Univariate Distributions_, volume 1, chapter 13.  Wiley, New York.

_S_e_e _A_l_s_o:

     Distributions for other standard distributions, including 'dlnorm'
     for the _Log_normal distribution.

_E_x_a_m_p_l_e_s:

     require(graphics)
     
     dnorm(0) == 1/sqrt(2*pi)
     dnorm(1) == exp(-1/2)/sqrt(2*pi)
     dnorm(1) == 1/sqrt(2*pi*exp(1))
     
     ## Using "log = TRUE" for an extended range :
     par(mfrow = c(2,1))
     plot(function(x) dnorm(x, log = TRUE), -60, 50,
          main = "log { Normal density }")
     curve(log(dnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("dnorm(x, log=TRUE)", adj = 0)
     mtext("log(dnorm(x))", col = "red", adj = 1)
     
     plot(function(x) pnorm(x, log.p = TRUE), -50, 10,
          main = "log { Normal Cumulative }")
     curve(log(pnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("pnorm(x, log=TRUE)", adj = 0)
     mtext("log(pnorm(x))", col = "red", adj = 1)
     
     ## if you want the so-called 'error function'
     erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1
     ## (see Abramowitz and Stegun 29.2.29)
     ## and the so-called 'complementary error function'
     erfc <- 